# Generated by Django 5.1.3 on 2024-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('activo', models.CharField(max_length=20)),
                ('prioridad', models.CharField(max_length=10)),
                ('numc', models.PositiveIntegerField()),
            ],
        ),
    ]
