# Generated by Django 5.1.3 on 2024-11-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
    ]
