# Generated by Django 5.1.3 on 2024-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estatus',
            field=models.CharField(default='activo', max_length=50),
        ),
    ]
