# Generated by Django 5.1.3 on 2024-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField(max_length=2)),
            ],
        ),
    ]
