# Generated by Django 5.1.3 on 2024-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
