# Generated by Django 5.1 on 2024-11-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_alter_clientes_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='edad',
            new_name='telefono',
        ),
    ]
